name: GitHub-Profile-Summary-Cards

on:
  push:
    branches:
      - main
  schedule: # execute every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  noofreuuuh-github-cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v6
        with:
          ref: github-profile-summary-cards-noofreuuuh

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: noofreuuuh
          BRANCH_NAME: github-profile-summary-cards-noofreuuuh
          UTC_OFFSET: "+1"
          AUTO_PUSH: "true"

  smouillour-github-cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v6
        with:
          ref: github-profile-summary-cards-smouillour

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: smouillour
          BRANCH_NAME: github-profile-summary-cards-smouillour
          UTC_OFFSET: "+1"
          AUTO_PUSH: "true"