name: GitHub-Profile-Summary-Cards

on:
  push:
    branches:
      - main
  schedule: # execute every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  get-paris-utc-offset:
    runs-on: ubuntu-latest
    outputs:
      utc_offset: ${{ steps.get-offset.outputs.utc_offset }}
    steps:
      - name: Get Paris UTC Offset
        id: get-offset
        run: |
          offset=$(TZ=Europe/Paris date +%z | awk '{printf "%+d", $1/100}')
          echo "utc_offset=$offset" >> $GITHUB_OUTPUT

      - name: Display UTC Offset
        run: echo "Paris UTC Offset is ${{ steps.get-offset.outputs.utc_offset }} hours"

  noofreuuuh-github-cards:
    runs-on: ubuntu-latest
    needs: get-paris-utc-offset
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: github-profile-summary-cards-noofreuuuh

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: noofreuuuh
          BRANCH_NAME: github-profile-summary-cards-noofreuuuh
          UTC_OFFSET: ${{ needs.get-paris-utc-offset.outputs.utc_offset }}
          AUTO_PUSH: "true"

  smouillour-github-cards:
    runs-on: ubuntu-latest
    needs: get-paris-utc-offset
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: github-profile-summary-cards-smouillour

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: smouillour
          BRANCH_NAME: github-profile-summary-cards-smouillour
          UTC_OFFSET: ${{ needs.get-paris-utc-offset.outputs.utc_offset }}
          AUTO_PUSH: "true"